find_package(SWIG REQUIRED)
include(UseSWIG)
find_package(Python3 REQUIRED COMPONENTS Interpreter Development.Module)
set(CMAKE_SWIG_OUTDIR ${CMAKE_BINARY_DIR}/python/pin_ik_python)
file(MAKE_DIRECTORY ${CMAKE_SWIG_OUTDIR})
configure_file(src/pin_ik_python/__init__.py ${CMAKE_SWIG_OUTDIR}/__init__.py COPYONLY)
configure_file(src/pin_ik_python/pin_ik.py ${CMAKE_SWIG_OUTDIR}/pin_ik.py COPYONLY)
set_source_files_properties(swig/pin_ik_wrap.i PROPERTIES CPLUSPLUS ON)
swig_add_library(pin_ik_wrap TYPE MODULE LANGUAGE python SOURCES swig/pin_ik_wrap.i)
target_link_libraries(pin_ik_wrap PRIVATE pin_ik Python3::Module)
set_target_properties(pin_ik_wrap PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SWIG_OUTDIR})
set(PIN_IK_PYTHON_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/python${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR}/site-packages/pin_ik_python" CACHE STRING "Python package install directory")
set_target_properties(pin_ik_wrap PROPERTIES INSTALL_RPATH "$ORIGIN/../../..")
install(TARGETS pin_ik_wrap LIBRARY DESTINATION ${PIN_IK_PYTHON_INSTALL_DIR})
install(FILES ${CMAKE_SWIG_OUTDIR}/pin_ik_wrap.py src/pin_ik_python/__init__.py src/pin_ik_python/pin_ik.py DESTINATION ${PIN_IK_PYTHON_INSTALL_DIR})
