cmake_minimum_required(VERSION 3.16)
project(pin_ik VERSION 2.2.0 LANGUAGES CXX)
include(GNUInstallDirs)
include(CTest)

# Import Pinocchio and its transitive targets in the scope shared by all subdirectories.
find_package(pinocchio 3.9.0 EXACT REQUIRED)

option(PIN_IK_BUILD_PYTHON "Build Python 3 bindings" ON)
option(PIN_IK_BUILD_EXAMPLES "Build standalone IK example" ON)
add_subdirectory(pin_ik_lib)
if(PIN_IK_BUILD_PYTHON)
  add_subdirectory(pin_ik_python)
endif()
if(PIN_IK_BUILD_EXAMPLES)
  add_subdirectory(pin_ik_examples)
endif()
if(BUILD_TESTING)
  add_subdirectory(tests)
endif()
