add_executable(standalone_tests standalone_tests.cpp)
target_link_libraries(standalone_tests PRIVATE trac_ik)
add_test(NAME cpp_standalone COMMAND standalone_tests ${CMAKE_CURRENT_SOURCE_DIR}/robot.urdf)
if(TRAC_IK_BUILD_PYTHON)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  add_test(NAME python_standalone COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/test_python.py ${CMAKE_CURRENT_SOURCE_DIR}/robot.urdf)
  set_tests_properties(python_standalone PROPERTIES ENVIRONMENT "PYTHONPATH=${CMAKE_BINARY_DIR}/python")
endif()
if(TRAC_IK_BUILD_EXAMPLES)
  add_test(NAME example_random_ik COMMAND ik_tests ${CMAKE_CURRENT_SOURCE_DIR}/robot.urdf base tip 100)
endif()
