find_package(SWIG REQUIRED)
include(UseSWIG)
find_package(Python3 REQUIRED COMPONENTS Interpreter Development.Module)
set(CMAKE_SWIG_OUTDIR ${CMAKE_BINARY_DIR}/python/trac_ik_python)
file(MAKE_DIRECTORY ${CMAKE_SWIG_OUTDIR})
configure_file(src/trac_ik_python/__init__.py ${CMAKE_SWIG_OUTDIR}/__init__.py COPYONLY)
configure_file(src/trac_ik_python/trac_ik.py ${CMAKE_SWIG_OUTDIR}/trac_ik.py COPYONLY)
set_source_files_properties(swig/trac_ik_wrap.i PROPERTIES CPLUSPLUS ON)
swig_add_library(trac_ik_wrap TYPE MODULE LANGUAGE python SOURCES swig/trac_ik_wrap.i)
target_link_libraries(trac_ik_wrap PRIVATE trac_ik Python3::Module)
set_target_properties(trac_ik_wrap PROPERTIES LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SWIG_OUTDIR})
set(TRAC_IK_PYTHON_INSTALL_DIR "${CMAKE_INSTALL_LIBDIR}/python${Python3_VERSION_MAJOR}.${Python3_VERSION_MINOR}/site-packages/trac_ik_python" CACHE STRING "Python package install directory")
set_target_properties(trac_ik_wrap PROPERTIES INSTALL_RPATH "$ORIGIN/../../..")
install(TARGETS trac_ik_wrap LIBRARY DESTINATION ${TRAC_IK_PYTHON_INSTALL_DIR})
install(FILES ${CMAKE_SWIG_OUTDIR}/trac_ik_wrap.py src/trac_ik_python/__init__.py src/trac_ik_python/trac_ik.py DESTINATION ${TRAC_IK_PYTHON_INSTALL_DIR})
